function pushbutton2_Callback(hObject, eventdata, handles, varargin)
[x,map]=uigetfile ({'*.jpg';'*.gif';'*.bmp';'*.TIFF';'*.*'},'Please pick the fabric to be examine');
I2=imresize(x, [42 113]);
h=uicontrol('style','pushbutton',...
            'units','pixels',...
            'position',[20 20 113+10 42+10],...
            'cdata',I2)